FROM ubuntu:latest
LABEL maintainer="vincent@vincenup.com"
USER root
ARG DEBIAN_FRONTEND=noninteractive
RUN true \
  && apt-get update --allow-releaseinfo-change && apt-get upgrade -y \
  && apt-get install -y apt-utils sudo vim curl wget git tar tree gnupg2 gnupg tmux python3 jq net-tools ntp ntpdate gpm locate dnsutils iotop openssh-server \
  && true
ARG USER_NAME=ansibleadmin
ARG CONTRASENA=123
RUN useradd -U $USER_NAME -m -s /bin/bash -G sudo
RUN echo "$USER_NAME:$CONTRASENA" | chpasswd
RUN echo "root:$CONTRASENA" | chpasswd
RUN echo "$USER_NAME ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN sed -i -re 's/^%sudo.*/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers
RUN ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -q -N ""
RUN sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
RUN service sshd restart
USER ansibleadmin